pid: /tmp/uaa.pid
mbus: nats://192.168.137.133:4222

uaa:
    host: 192.168.137.1
    port: 8080

tags:
    component: uaa

jvm_args: -Xmx512m
spring_profiles: mysql

database:
    url: jdbc:mysql://192.168.137.133:3306/uaa
    username: root
    password: 123456

cloud_controller:
    database:
        url: jdbc:mysql://192.168.137.133:3306/cloud_controller
        username: root
        password: 123456

jwt:
    token:
        signing-key: 'tokensecret'
        verification-key: 'tokensecret'
        
scim:
    userids_enabled: false
    user.override: true
    users:
        - admin|admin|scim.write,scim.read,openid,cloud_controller.admin
        - testuser|testuser|scim.write,scim.read,openid,cloud_controller.user

oauth:
    clients:
        admin:
            authorized-grant-types: client_credentials
            scope: clients.read,clients.write,clients.secret,uaa.admin,scim.read,scim.write
            authorities: clients.read,clients.write,clients.secret,uaa.admin,scim.read,scim.write
            id: admin
            secret: adminsecret
            resource-ids: none
        cloud_controller:
            authorized-grant-types: client_credentials
            authorities: scim.read,scim.write,password.write,uaa.resource
            id: cloud_controller
            secret: cloudcontrollersecret
            resource-ids: none
            access-token-validity: 604800
        vmc:
            authorized-grant-types: implicit
            authorities: uaa.none
            id: vmc
            resource-ids: none
            redirect-uri: http://uaa.cloudfoundry.com/redirect/vmc,https://uaa.cloudfoundry.com/redirect/vmc
            access-token-validity: 604800
        cf:
            authorized-grant-types: implicit
            authorities: uaa.none
            scope: uaa.admin,scim.read,scim.write,openid,password.write,cloud_controller.admin,cloud_controller.read,cloud_controller.write
            id: cf
            resource-ids: none
            redirect-uri: http://uaa.cloudfoundry.com/redirect/cf,https://uaa.cloudfoundry.com/redirect/cf
            access-token-validity: 604800
            autoapprove: true
        login:
            id: login
            secret: loginsecret
            authorized-grant-types: client_credentials
            authorities: cloud_controller.admin,loud_controller.write,uaa.admin,scim.read,scim.write,openid,password.write
            scope: cloud_controller.admin,cloud_controller.write,uaa.admin,scim.read,scim.write,openid,password.write
